version: '3.7'

services:
  web:
    image: comp4321-se
    build: .
    restart: always
    environment:
      SE_DB_BASE_PATH: /srv/rocksdb
    ports:
      - 8080
    volumes:
      - rocksdb:/srv/rocksdb
  ui:
    image: comp4321-se-ui
    build: ../comp4321-proj-ui
    restart: always
    depends_on:
      - web
    ports:
      - 3000:80

volumes:
  rocksdb:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/db
